# Generated by Django 4.0.3 on 2024-12-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
