# Generated by Django 4.0.3 on 2024-12-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0006_alter_course_created_at_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
