# Generated by Django 4.0.3 on 2024-12-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0007_staff_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='user_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
