# Generated by Django 4.0.3 on 2024-12-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0011_remove_staff_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user_type',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Student', 'Student')], default='null', max_length=10),
        ),
    ]
