# Generated by Django 4.0.3 on 2024-12-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0012_staff_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user_type',
        ),
    ]
